---
- name: Install Zabbix repository
  dnf: 
    disable_gpg_check: yes
    name: https://repo.zabbix.com/zabbix/5.5/rhel/8/x86_64/zabbix-release-5.5-1.el8.noarch.rpm
    state: present

- name: Install Zabbix-agent on RedHat Family
  dnf:
    name=zabbix-agent
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - zabbix-agent systemd

- name: Edit Zabbix config
  template:
    src: templates/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Add node exporter user
  user:
    name: node_exporter
    shell: /bin/false
    create_home: no

- name: Download and unpack Node Exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: Copy Node Exporter to bin
  copy:
    src: /root/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/bin
    remote_src: yes
    owner: node_exporter
    mode: u+rx,g-wx,o-rwx

- name: Add Node Exporter service
  template:
    src: templates/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - node exporter systemd